/*

 CINE2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : font.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Cine2Width 20
#define Cine2Height 18
#define Cine2Bank 0

extern unsigned char Cine2[];

/* End of CINE2.H */
