/*

 CINE1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : font.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Cine1Width 20
#define Cine1Height 18
#define Cine1Bank 0

extern unsigned char Cine1[];

/* End of CINE1.H */
