/*

 CINE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Thomas\Desktop\GameBoy Development\Mona and the Witch's Hat\res\cinematics.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define cineWidth 20
#define cineHeight 18
#define cineBank 0

extern unsigned char cine[];

/* End of CINE.H */
