/*

 MAP3.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 128 x 20
   Tile set      : tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map3Width 128
#define map3Height 20
#define map3Bank 0

extern unsigned char map3[];

/* End of MAP3.H */
