/*

 MAP4.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map4Width 32
#define map4Height 18
#define map4Bank 0

extern unsigned char map4[];

/* End of MAP4.H */
